services:
  server:
    build: ./mern/server
    container_name: mern-server
    ports:
      - "${SERVER_HOST_PORT}:${SERVER_PORT}"
    environment:
      - ATLAS_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
    networks:
      - mern-example-network
    depends_on:
      - mongodb
  client:
    build: ./mern/client
    container_name: mern-client
    ports:
      - "${CLIENT_HOST_PORT}:${CLIENT_PORT}"
    depends_on:
      - server
    networks:
      - mern-example-network

  mongodb:
    ports:
      - "${MONGO_HOST_PORT}:${MONGO_PORT}"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mern-example-network
    image: mongo:8
    volumes:
      - mongo_data2:/data/db

volumes:
  mongo_data2:

networks:
  mern-example-network:
    driver: bridge
